<?php

namespace Kitpages\UserGeneratedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentPostRepository extends EntityRepository
{
    public function findByItemReference($itemReference, $order = 'desc', $limit = null, $offset = null)
    {
        $query = $this->_em
            ->createQuery("
                SELECT p
                FROM KitpagesUserGeneratedBundle:CommentPost p
                WHERE p.itemReference = :itemReference
                ORDER BY p.position ".$order)
            ->setParameter("itemReference", $itemReference);
        if ($limit !== null) {
            $query->setMaxResults($limit);
        }
        if ($offset != null) {
            $query->setFirstResult($offset);
        }
        return $query->getResult();
    }

}